[project]
name = "lyricutils"
version = "0.1.0"
description = "A library used to download, create, and align lyrics to a song with multiple backend choices"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.ruff.format]
quote-style = "double"
skip-magic-trailing-comma = false
